### ISSUE TITLE
Component traits

### ISSUE THREAD

**Issue by Dreyri** [Dreyri/matter#21]
A list of component traits to implement:

explicit:
- [x] #16 `depends_on = std::tuple<types>`
- [x] #22 specify storage type
- [x] #23 component variants

implicit:
- [x] #24 empty component
- [ ] #25 automatically define storage type if not defined
